### ISSUE TITLE
Improve accessibility of the example plot in data section

### ISSUE THREAD

**Issue by jonatanklosko** [livebook-dev/livebook_website#11]
The weather plot we have is an SVG image and has a bunch of `aria-` attributes. @mikolysz you mentioned it's hard to skip the image, any ideas on how we can improve that? Currently we just use a regular `<img>` tag with empty `alt` text.

**Comment by mikolysz** [comment]
Screen readers usually have a way to skip over a container such as a list or a table. If we're not interested in whatever is in that container, we can just use such a shortcut to find the first element past that container. Perhaps giving the chart a role of "region" would make screen readers treat it that way, not sure though.

If we can't find a way to mark the chart as a skippable region, we can always add a skip link that just skips over it, but that's a much clunkier solution.

**Comment by jonatanklosko** [comment]
Closed via #13.
