### ISSUE TITLE
Wrong version installed

### ISSUE THREAD

**Issue by epinault** [livebook-dev/livebook_website#14]
I followed this instruction but it installed 0.1.0 instead of 0.3.0. https://github.com/livebook-dev/livebook_website/blob/55d326267101b123d37f9f6bcd1bc981aa14eae2/src/partials/install_instructions.html#L125

I was able to install the latest using  

```
 mix escript.install hex livebook 0.3.0
```

I am using elixir 1.12.1 locally, OTP 24.1 and latest hex

**Comment by jonatanklosko** [comment]
Hey @epinault! There was an issue with hex package resolution that caused this (together with a specific incompatibility in our dependency versions). Both of these issues should be addressed by now though. Just to make sure, could you please upgrade hex with `mix local.hex --force` and confirm the weird behavior persists? For the record, the latest version is 0.3.2 now :)

**Comment by epinault** [comment]
that was it! thanks! I think the --force is what helped
