### ISSUE TITLE
Add Elixir version

### ISSUE THREAD

**Issue by thecristen** [livebook-dev/livebook_website#16]
https://github.com/livebook-dev/livebook_website/blob/564512eef816ed62b2734b64879d9e286191b534/src/partials/install_instructions.html#L115

It would be a nice improvement if the page mentioned which version of Elixir you need. I had to get to the livebook Github repo to find that I will need Elixir v1.13 or later.

**Comment by josevalim** [comment]
Good call. Can you please send a PR? I think we could simply add "v1.13+" to the snippet you sent. :)

**Comment by jonatanklosko** [comment]
Closed via #17.
